apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: chud
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chud
    app.kubernetes.io/part-of: byoc-app-hfmy
  name: chud
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: chud
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: chud
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-wyij-tenant/byoc-app-hfmy/chud@sha256:82df9d3ed8db458a371dd4ac35f8a13e25a8485c637d9f1dfb395504598d25be
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
